### ISSUE TITLE
Release v2 to the Github Actions Marketplace

### ISSUE THREAD

**Issue by ajgrover** [anna-money/github-actions-npm#5]
When you come across this package on Github you see the following versions and install instructions:

### Marketplace listing:
<img width="1072" alt="Screen Shot 2021-02-04 at 11 46 25" src="https://user-images.githubusercontent.com/3088615/106946927-9dbb4200-66de-11eb-9883-371d1a98d883.png">

### Actions sidebar:
<img width="572" alt="Screen Shot 2021-02-04 at 11 46 43" src="https://user-images.githubusercontent.com/3088615/106946981-a90e6d80-66de-11eb-8ac1-39d78397b6de.png">

These are out of date with what's in the README. Can you publish the latest version so it's clear how to use this action without having to look at the repo?

**Comment by arslanbekov** [comment]
@ajgrover yes, thanks! Apparently, it updated itself over time, we also pushed the last tag (it was not launched by our mistake) into the marketplace.
